"""create initial tables

Revision ID: d2a6a47f190c
Revises:
Create Date: 2025-04-12 09:43:46.854430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2a6a47f190c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixed_accidity", sa.Float(), nullable=False),
        sa.Column("volatile_acidity", sa.Float(), nullable=False),
        sa.Column("citric_acid", sa.Float(), nullable=False),
        sa.Column("residual_sugar", sa.Float(), nullable=False),
        sa.Column("chlorides", sa.Float(), nullable=False),
        sa.Column("free_sulfur_dioxide", sa.Float(), nullable=False),
        sa.Column("total_sulfur_dioxide", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("pH", sa.Float(), nullable=False),
        sa.Column("sulphates", sa.Float(), nullable=False),
        sa.Column("alcohol", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluated_wines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wine_id", sa.Integer(), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wine_id"],
            ["wines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluated_wines")
    op.drop_table("wines")
    # ### end Alembic commands ###
